### PR TITLE
Remove the terrible malaware lmao

### PR DESCRIPTION
**Pull request by KDot227**

### CODE REVIEW

**Comment by xpierroz** [comment]
all their repositories have this shit 💀

**Comment by KDot227** [comment]
> all their repositories have this shit 💀

1 print and their obf gone 💀

**Comment by CrippinDog3** [comment]
is this a malware?

**Comment by xpierroz** [comment]
yes this is a malware, you can on the line 2

**Comment by azgaresncf** [comment]
It is completely a malware.

**Comment by CrippinDog3** [comment]
How do i remove it if i got infected?

**Comment by CrippinDog3** [comment]
> It is completely a malware.


How do i remove it if i got infected?

**Comment by azgaresncf** [comment]
> > It is completely a malware.
> 
> 
> How do i remove it if i got infected?
> 
> 
> 
> 

First, change your credentials.
Second -> https://github.com/Just-Chakal/discordcleaner

**Comment by CrippinDog3** [comment]
> > > It is completely a malware.
> > 
> > 
> > How do i remove it if i got infected?
> 
> First, change your credentials. Second -> https://github.com/Just-Chakal/discordcleaner

what is that?

**Comment by azgaresncf** [comment]
> > > > It is completely a malware.
> > > 
> > > 
> > > How do i remove it if i got infected?
> > 
> > First, change your credentials. Second -> https://github.com/Just-Chakal/discordcleaner
> 
> what is that?

It is a safe tool to clean up your discord so that you won't have your credentials grabbed anymore

**Comment by CrippinDog3** [comment]
> > > > > It is completely a malware.
> > > > 
> > > > 
> > > > How do i remove it if i got infected?
> > > 
> > > 
> > > First, change your credentials. Second -> https://github.com/Just-Chakal/discordcleaner
> > 
> > 
> > what is that?
> 
> It is a safe tool to clean up your discord so that you won't have your credentials grabbed anymore

How do i know its safe?

**Comment by azgaresncf** [comment]
> > > > > > It is completely a malware.
> > > > > 
> > > > > 
> > > > > How do i remove it if i got infected?
> > > > 
> > > > 
> > > > First, change your credentials. Second -> https://github.com/Just-Chakal/discordcleaner
> > > 
> > > 
> > > what is that?
> > 
> > It is a safe tool to clean up your discord so that you won't have your credentials grabbed anymore
> 
> How do i know its safe?

Check the javascript code

**Comment by azgaresncf** [comment]
I can prove it to you if you want to

**Comment by CrippinDog3** [comment]
> I can prove it to you if you want to

ye

**Comment by azgaresncf** [comment]
> > I can prove it to you if you want to
> 
> ye
> 

Add me to Discord, it is on my profile

**Comment by CrippinDog3** [comment]
dont go, gimme ur tag

**Comment by azgaresncf** [comment]
> dont go, gimme ur tag

don't need it, dw https://discord.com/users/817817254187892767

**Comment by CrippinDog3** [comment]
> > dont go, gimme ur tag
> 
> don't need it, dw https://discord.com/users/817817254187892767

it doesnt go

**Comment by azgaresncf** [comment]
> > > dont go, gimme ur tag
> > 
> > don't need it, dw https://discord.com/users/817817254187892767
> 
> it doesnt go

What the hell

**Comment by azgaresncf** [comment]
> > > dont go, gimme ur tag
> > 
> > don't need it, dw https://discord.com/users/817817254187892767
> 
> it doesnt go

Give me your username and tag, I will add you

**Comment by CrippinDog3** [comment]
> 

no, gimme urs

**Pull request closed without merging**
